# Generated by Django 5.2.2 on 2025-10-19 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер карты"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="Баллы"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("bronze", "Бронзовый"),
                            ("silver", "Серебряный"),
                            ("gold", "Золотой"),
                            ("platinum", "Платиновый"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_card",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта лояльности",
                "verbose_name_plural": "Карты лояльности",
                "ordering": ["-points"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earned", "Начислено"),
                            ("spent", "Потрачено"),
                            ("bonus", "Бонус"),
                            ("refund", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип транзакции",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="Баллы")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="paint_shop_project.loyaltycard",
                        verbose_name="Карта",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="paint_shop_project.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция лояльности",
                "verbose_name_plural": "Транзакции лояльности",
                "ordering": ["-created_at"],
            },
        ),
    ]
