# Generated by Django 5.2.2 on 2025-10-19 22:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paint_shop_project",
            "0003_promocode_notification_searchhistory_viewhistory_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название раздела"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("icon", models.CharField(max_length=50, verbose_name="Иконка")),
                (
                    "color",
                    models.CharField(
                        default="#ff6b9d", max_length=7, verbose_name="Цвет"
                    ),
                ),
                (
                    "cashback_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=3,
                        verbose_name="Множитель кешбэка",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Специальный раздел",
                "verbose_name_plural": "Специальные разделы",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_newsletter_subscribed",
            field=models.BooleanField(
                default=True, verbose_name="Подписка на рассылку"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_preferences",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки уведомлений"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_delivery_time",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Предпочитаемое время доставки"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_source",
            field=models.CharField(
                default="website", max_length=50, verbose_name="Источник регистрации"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_cashback_earned",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Общий кешбэк"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_cashback_spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Потраченный кешбэк",
            ),
        ),
        migrations.CreateModel(
            name="CashbackTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма кешбэка"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earned", "Заработан"),
                            ("spent", "Потрачен"),
                            ("expired", "Истек"),
                        ],
                        max_length=20,
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата транзакции"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashback_transactions",
                        to="paint_shop_project.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashback_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция кешбэка",
                "verbose_name_plural": "Транзакции кешбэка",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=100, verbose_name="Имя сотрудника"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата оценки"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_ratings",
                        to="paint_shop_project.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка сотрудника",
                "verbose_name_plural": "Оценки сотрудников",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыт"),
                            ("in_progress", "В работе"),
                            ("resolved", "Решен"),
                            ("closed", "Закрыт"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("urgent", "Срочный"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("order", "Заказ"),
                            ("delivery", "Доставка"),
                            ("payment", "Оплата"),
                            ("product", "Товар"),
                            ("loyalty", "Программа лояльности"),
                            ("technical", "Техническая поддержка"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="paint_shop_project.order",
                        verbose_name="Связанный заказ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тикет поддержки",
                "verbose_name_plural": "Тикеты поддержки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "is_staff_response",
                    models.BooleanField(default=False, verbose_name="Ответ сотрудника"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата ответа"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор ответа",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="paint_shop_project.supportticket",
                        verbose_name="Тикет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ поддержки",
                "verbose_name_plural": "Ответы поддержки",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cashback_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=3,
                        verbose_name="Множитель кешбэка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_by",
                        to="paint_shop_project.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Любимая категория",
                "verbose_name_plural": "Любимые категории",
                "ordering": ["-created_at"],
                "unique_together": {("user", "category")},
            },
        ),
        migrations.CreateModel(
            name="UserSpecialSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата присоединения"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="paint_shop_project.specialsection",
                        verbose_name="Раздел",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_sections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие в разделе",
                "verbose_name_plural": "Участия в разделах",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "section")},
            },
        ),
    ]
