# Generated by Django 5.2.2 on 2025-10-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paint_shop_project",
            "0004_specialsection_user_is_newsletter_subscribed_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                ("code", models.CharField(max_length=6, verbose_name="SMS-код")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Использован"),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("registration", "Регистрация"),
                            ("login", "Вход"),
                            ("password_reset", "Сброс пароля"),
                        ],
                        default="registration",
                        max_length=20,
                        verbose_name="Тип верификации",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS-верификация",
                "verbose_name_plural": "SMS-верификации",
                "ordering": ["-created_at"],
            },
        ),
    ]
