# Generated by Django 5.2.2 on 2025-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0005_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Срок годности"),
        ),
        migrations.AddField(
            model_name="product",
            name="has_expiry_date",
            field=models.BooleanField(
                default=False, verbose_name="Имеет срок годности"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="production_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата производства"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shelf_life_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Срок хранения (дни)"
            ),
        ),
    ]
