# Generated by Django 5.2.2 on 2025-10-24 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0006_add_expiry_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("javascript", "JavaScript ошибка"),
                            ("server", "Серверная ошибка"),
                            ("validation", "Ошибка валидации"),
                            ("payment", "Ошибка платежа"),
                            ("cart", "Ошибка корзины"),
                            ("other", "Другая ошибка"),
                        ],
                        max_length=20,
                        verbose_name="Тип ошибки",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение об ошибке")),
                (
                    "stack_trace",
                    models.TextField(
                        blank=True, null=True, verbose_name="Стек вызовов"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, null=True, verbose_name="URL страницы"),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Исправлено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ошибка",
                "verbose_name_plural": "Ошибки",
                "ordering": ["-created_at"],
            },
        ),
    ]
