# Generated by Django 5.2.2 on 2025-10-24 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0007_add_error_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritecategory",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="Скидка (%)",
            ),
        ),
        migrations.AddField(
            model_name="favoritecategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
