# Generated by Django 5.2.2 on 2025-10-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0008_add_favorite_category_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="actual_delivery_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Фактическое время доставки"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="courier_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Имя курьера"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="courier_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Телефон курьера"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ожидаемое время доставки"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Номер отслеживания"
            ),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("confirmed", "Подтверждён"),
                            ("ready", "Готов"),
                            ("in_transit", "В пути"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменён"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время изменения"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "courier_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Имя курьера"
                    ),
                ),
                (
                    "courier_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Телефон курьера"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="paint_shop_project.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса заказа",
                "verbose_name_plural": "История статусов заказов",
                "ordering": ["-timestamp"],
            },
        ),
    ]
