# Generated by Django 5.2.2 on 2025-10-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0009_add_order_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltycard",
            name="total_spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Общая сумма покупок",
            ),
        ),
    ]
