# Generated by Django 5.2.2 on 2025-10-24 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0010_add_total_spent_to_loyalty_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="title",
        ),
        migrations.AddField(
            model_name="promotion",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Процент"), ("fixed", "Фиксированная сумма")],
                default="percentage",
                max_length=20,
                verbose_name="Тип скидки",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Размер скидки"
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="min_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Минимальная сумма заказа",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="name",
            field=models.CharField(
                default="Акция", max_length=200, verbose_name="Название акции"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="description",
            field=models.TextField(default="Описание акции", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала"
            ),
        ),
        migrations.CreateModel(
            name="UserPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Размер скидки"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата использования"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_promotions",
                        to="paint_shop_project.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="paint_shop_project.promotion",
                        verbose_name="Акция",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_promotions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Использованная акция",
                "verbose_name_plural": "Использованные акции",
                "unique_together": {("user", "promotion", "order")},
            },
        ),
    ]
