# Generated by Django 5.2.2 on 2025-10-29 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0013_order_fulfillment_store_deliveryslot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        max_length=20, verbose_name="Бренд (Visa/MasterCard)"
                    ),
                ),
                (
                    "last4",
                    models.CharField(max_length=4, verbose_name="Последние 4 цифры"),
                ),
                (
                    "expiry_month",
                    models.PositiveSmallIntegerField(verbose_name="Месяц истечения"),
                ),
                (
                    "expiry_year",
                    models.PositiveSmallIntegerField(verbose_name="Год истечения"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Способ оплаты",
                "verbose_name_plural": "Способы оплаты",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("n_for_m", "N за M (например 3 за 2)"),
                            (
                                "percent_category",
                                "Скидка % на категорию при мин. количестве",
                            ),
                        ],
                        max_length=30,
                        verbose_name="Тип правила",
                    ),
                ),
                ("n", models.PositiveIntegerField(default=0, verbose_name="N")),
                ("m", models.PositiveIntegerField(default=0, verbose_name="M")),
                (
                    "percent",
                    models.PositiveIntegerField(default=0, verbose_name="Скидка %"),
                ),
                (
                    "min_qty",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Мин. количество"
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "per_user_once",
                    models.BooleanField(
                        default=False, verbose_name="Одноразовая для пользователя"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="paint_shop_project.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило промо",
                "verbose_name_plural": "Правила промо",
                "ordering": ["-created_at"],
            },
        ),
    ]
