# Generated by Django 5.2.2 on 2025-10-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0014_paymentmethod_promorule"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("backup", "Создание резервной копии"),
                            ("restore", "Восстановление из резервной копии"),
                        ],
                        max_length=20,
                        verbose_name="Операция",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Успешно"),
                            ("failed", "Ошибка"),
                            ("in_progress", "В процессе"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "file_path",
                    models.TextField(
                        help_text="Абсолютный путь к файлу резервной копии",
                        verbose_name="Путь к файлу",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (байты)"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало операции"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание операции"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="database_backups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резервная копия БД",
                "verbose_name_plural": "Резервные копии БД",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="paint_shop__started_57df1e_idx"
                    ),
                    models.Index(
                        fields=["operation", "status"],
                        name="paint_shop__operati_06d3c5_idx",
                    ),
                ],
            },
        ),
    ]
