# Generated by Django 5.2.2 on 2025-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0015_databasebackup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID чата в Telegram для получения уведомлений",
                null=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_notifications_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Включить Telegram уведомления"
            ),
        ),
    ]
