# Generated by Django 5.2.2 on 2025-11-02 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0016_user_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courier_deliveries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Курьер",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("manager", "Менеджер магазина"),
                    ("picker", "Сборщик"),
                    ("courier", "Курьер"),
                    ("delivery", "Доставщик"),
                    ("customer", "Покупатель"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Название роли",
            ),
        ),
        migrations.CreateModel(
            name="OrderDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает доставки"),
                            ("assigned", "Назначена"),
                            ("picked_up", "Забрал из магазина"),
                            ("in_transit", "В пути"),
                            ("delivered", "Доставлен"),
                            ("failed", "Не доставлен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус доставки",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Назначено"
                    ),
                ),
                (
                    "picked_up_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Забрано"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Доставлено"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий доставщика"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "delivery_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Доставщик",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_tracking",
                        to="paint_shop_project.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка заказа",
                "verbose_name_plural": "Доставки заказов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderPicking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает сборки"),
                            ("in_progress", "Собирается"),
                            ("completed", "Собран"),
                            ("missing_items", "Недостаточно товаров"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус сборки",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало сборки"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание сборки"
                    ),
                ),
                (
                    "missing_items_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий о недостающих товарах"
                    ),
                ),
                (
                    "notified_customer",
                    models.BooleanField(
                        default=False, verbose_name="Покупатель уведомлен"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking",
                        to="paint_shop_project.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "picker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сборщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сборка заказа",
                "verbose_name_plural": "Сборки заказов",
                "ordering": ["-created_at"],
            },
        ),
    ]
