# Generated by Django 5.2.2 on 2025-11-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0018_update_role_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_deliver_orders",
            field=models.BooleanField(
                default=False, verbose_name="Может доставлять заказы"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_manage_store",
            field=models.BooleanField(
                default=False, verbose_name="Может управлять магазином"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_pick_orders",
            field=models.BooleanField(
                default=False, verbose_name="Может собирать заказы"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_staff_role",
            field=models.BooleanField(default=False, verbose_name="Роль персонала"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("manager", "Менеджер магазина"),
                    ("picker", "Сборщик"),
                    ("delivery", "Доставщик"),
                    ("customer", "Покупатель"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Название роли",
            ),
        ),
    ]
