# Generated by Django 5.2.2 on 2025-11-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paint_shop_project",
            "0019_role_can_deliver_orders_role_can_manage_store_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название метрики"
                    ),
                ),
                ("value", models.FloatField(verbose_name="Значение")),
                (
                    "labels",
                    models.JSONField(blank=True, default=dict, verbose_name="Метки"),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("counter", "Counter"),
                            ("gauge", "Gauge"),
                            ("histogram", "Histogram"),
                        ],
                        default="counter",
                        max_length=20,
                        verbose_name="Тип метрики",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика",
                "verbose_name_plural": "Метрики",
                "db_table": "metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["name", "timestamp"], name="metrics_name_8083e4_idx"
                    )
                ],
            },
        ),
    ]
