# Generated by Django 5.2.2 on 2025-11-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0020_create_default_roles"),
        ("paint_shop_project", "0021_add_product_batch"),
    ]

    operations = []
