# Generated by Django 5.2.2 on 2025-11-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0024_add_picker_action_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databasebackup",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="courier",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="order",
        ),
        migrations.RemoveField(
            model_name="discount",
            name="product",
        ),
        migrations.AlterUniqueTogether(
            name="storeinventory",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="storeinventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="storeinventory",
            name="store",
        ),
        migrations.AlterModelOptions(
            name="favoritecategory",
            options={
                "verbose_name": "Любимая категория",
                "verbose_name_plural": "Любимые категории",
            },
        ),
        migrations.AlterModelOptions(
            name="useraddress",
            options={
                "ordering": ["-is_default", "-updated_at"],
                "verbose_name": "Адрес пользователя",
                "verbose_name_plural": "Адреса пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="userspecialsection",
            options={
                "verbose_name": "Раздел пользователя",
                "verbose_name_plural": "Разделы пользователей",
            },
        ),
        migrations.RenameIndex(
            model_name="batchauditlog",
            new_name="paint_shop__batch_i_96f7a1_idx",
            old_name="paint_shop_batch_i_batch_i_idx",
        ),
        migrations.RenameIndex(
            model_name="batchauditlog",
            new_name="paint_shop__action_609a6e_idx",
            old_name="paint_shop_batch_i_action__idx",
        ),
        migrations.RenameIndex(
            model_name="batchauditlog",
            new_name="paint_shop__user_id_61e259_idx",
            old_name="paint_shop_batch_i_user_i_idx",
        ),
        migrations.RenameIndex(
            model_name="pickeractionlog",
            new_name="paint_shop__picker__fed1c2_idx",
            old_name="paint_shop_picker_picker__idx",
        ),
        migrations.RenameIndex(
            model_name="pickeractionlog",
            new_name="paint_shop__order_i_71060c_idx",
            old_name="paint_shop_picker_order__idx",
        ),
        migrations.RenameIndex(
            model_name="pickeractionlog",
            new_name="paint_shop__action__0b287c_idx",
            old_name="paint_shop_picker_action__idx",
        ),
        migrations.RenameIndex(
            model_name="productbatch",
            new_name="paint_shop__product_5b3a74_idx",
            old_name="paint_shop_product_expiry_idx",
        ),
        migrations.RenameIndex(
            model_name="productbatch",
            new_name="paint_shop__expiry__a35b2d_idx",
            old_name="paint_shop_expiry_date_idx",
        ),
        migrations.RemoveField(
            model_name="userspecialsection",
            name="joined_at",
        ),
        migrations.AddField(
            model_name="errorlog",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="paint_shop_project.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="intercom_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Код домофона"
            ),
        ),
        migrations.AddField(
            model_name="userspecialsection",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="favoritecategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="paint_shop_project.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(
                fields=["remaining_quantity"], name="paint_shop__remaini_b46198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(
                fields=["expiry_date", "remaining_quantity"],
                name="paint_shop__expiry__78d553_idx",
            ),
        ),
        migrations.DeleteModel(
            name="DatabaseBackup",
        ),
        migrations.DeleteModel(
            name="Delivery",
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
        migrations.DeleteModel(
            name="StoreInventory",
        ),
    ]
