# Generated by Django 5.2.2 on 2025-11-12 20:23

from django.db import migrations, models
from django.utils import timezone


def set_created_at_for_existing(apps, schema_editor):
    """Устанавливает created_at для существующих записей"""
    UserSpecialSection = apps.get_model('paint_shop_project', 'UserSpecialSection')
    UserSpecialSection.objects.filter(created_at__isnull=True).update(created_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0025_remove_databasebackup_created_by_and_more"),
    ]

    operations = [
        migrations.RunPython(set_created_at_for_existing, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userspecialsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления"),
        ),
    ]
