# Generated by Django 5.2.2 on 2025-11-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0027_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Карта"),
                    ("online", "Онлайн"),
                    ("sbp", "СБП"),
                    ("cash", "Наличные"),
                    ("cashback", "Кешбэк"),
                ],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Карта"),
                    ("online", "Онлайн"),
                    ("sbp", "СБП"),
                    ("cash", "Наличные"),
                    ("cashback", "Кешбэк"),
                ],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
