# Generated by Django 5.2.2 on 2025-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0028_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Любимый товар",
                "verbose_name_plural": "Любимые товары",
            },
        ),
        migrations.AddField(
            model_name="favorite",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
