# Generated by Django 5.2.2 on 2025-11-17 14:54

from django.db import migrations, models
from django.db.models import F


def populate_amount_due(apps, schema_editor):
    Order = apps.get_model("paint_shop_project", "Order")
    Order.objects.filter(models.Q(amount_due=0) | models.Q(amount_due__isnull=True)).update(
        amount_due=F("total_amount")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0030_databasebackup"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Сумма к оплате",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cashback_used",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Списанный кешбэк",
            ),
        ),
        migrations.RunPython(populate_amount_due, migrations.RunPython.noop),
    ]
