# Generated by Django 5.2.2 on 2025-11-17 16:28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paint_shop_project", "0031_order_amount_due_order_cashback_used"),
    ]

    def _set_default_discount(apps, schema_editor):
        FavoriteCategory = apps.get_model("paint_shop_project", "FavoriteCategory")
        default_value = getattr(settings, "FAVORITE_CATEGORY_DISCOUNT", 10)
        FavoriteCategory.objects.filter(discount_percent__lte=0).update(
            discount_percent=default_value
        )

    operations = [
        migrations.AlterField(
            model_name="favoritecategory",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="Скидка (%)",
            ),
        ),
        migrations.RunPython(_set_default_discount, migrations.RunPython.noop),
    ]
