"""
Django settings for Жевжик project.

Магазин продуктов "Жевжик" - милый поросенок для ваших покупок!

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="django-insecure-#9hn(4ifja!6me!udysk)vzm5f8=wr7xt)4_5&bva#-4nuy%-h")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "paint_shop_project",
    'django_prometheus',
    # REST API
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'corsheaders',
    'django_filters',
    # Celery (опционально, если установлены пакеты)
    # Раскомментируйте, если установлены celery, django-celery-beat, django-celery-results
    # 'django_celery_beat',
    # 'django_celery_results',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Для статических файлов в production
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "paint_shop_project.middleware.SuppressSuccessMessagesMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "paint_shop_project.middleware.TemplateSyntaxErrorLoggingMiddleware",
    "paint_shop_project.prometheus_middleware.PrometheusMetricsMiddleware",
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = "paint_shop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "paint_shop_project" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "paint_shop_project.context_processors.dashboard_url",
            ],
        },
    },
]

WSGI_APPLICATION = "paint_shop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"postgresql://postgres:1@localhost:5432/Jevjik_shop",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Настройки для резервного копирования PostgreSQL
# Автоматический поиск бинарников PostgreSQL
try:
    import glob
    # Список стандартных путей для поиска PostgreSQL на Windows
    _postgres_common_paths = [
        r"C:\Program Files\PostgreSQL",
        r"C:\Program Files (x86)\PostgreSQL",
    ]

    # Автоматический поиск каталога bin PostgreSQL
    DATABASE_BACKUP_BIN_DIR = None
    for base_path in _postgres_common_paths:
        if os.path.exists(base_path):
            # Ищем последнюю установленную версию
            versions = sorted(glob.glob(os.path.join(base_path, "*/bin/pg_dump.exe")), reverse=True)
            if versions:
                DATABASE_BACKUP_BIN_DIR = str(Path(versions[0]).parent)
                break
except Exception:
    # Если не удалось найти автоматически, можно указать вручную
    DATABASE_BACKUP_BIN_DIR = None

# Если не найдено автоматически, можно указать вручную:
# DATABASE_BACKUP_BIN_DIR = r"C:\Program Files\PostgreSQL\15\bin"

# Или укажите конкретные пути:
# DATABASE_BACKUP_BIN = {
#     "pg_dump": r"C:\Program Files\PostgreSQL\15\bin\pg_dump.exe",
#     "pg_restore": r"C:\Program Files\PostgreSQL\15\bin\pg_restore.exe",
#     "psql": r"C:\Program Files\PostgreSQL\15\bin\psql.exe",
# }

# Или список каталогов для поиска:
# DATABASE_BACKUP_BIN_DIRS = [
#     r"C:\Program Files\PostgreSQL\15\bin",
#     r"C:\Program Files\PostgreSQL\14\bin",
# ]



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = 'paint_shop_project.User'

# Logout settings
LOGOUT_REDIRECT_URL = '/'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'isip_a.v.korgopolov@mpt.ru'
# Админы для уведомлений
ADMINS = [('Admin', 'isip_a.v.korgopolov@mpt.ru')]  # Используем реальный email вместо example.com
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'isip_a.v.korgopolov@mpt.ru'
EMAIL_HOST_PASSWORD = 'upkp abqq ewuu dipm'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default="http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000",
    cast=Csv()
)

CORS_ALLOW_CREDENTIALS = True

# CSRF Settings для production
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000',
    cast=Csv()
)

# Security settings для production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': True,
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'paint_shop_project': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Celery Configuration
# Используем локальное хранилище для результатов (для разработки)
# В продакшене используйте Redis или RabbitMQ
CELERY_BROKER_URL = 'memory://'  # Для разработки на Windows
CELERY_RESULT_BACKEND = 'django-db'  # Сохраняем результаты в БД
CELERY_RESULT_EXTENDED = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Планировщик задач
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Настройки для автоматических бэкапов
BACKUP_SCHEDULE_HOUR = 2  # 2 часа ночи
BACKUP_SCHEDULE_MINUTE = 0
BACKUP_ENABLE_NOTIFICATIONS = True  # Включить уведомления по email

# Telegram Bot настройки
# Получить токен можно у @BotFather в Telegram
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', None)  # Установите токен через переменную окружения
TELEGRAM_ENABLE_NOTIFICATIONS = True  # Включить Telegram уведомления

# Celery Configuration
# Используем локальное хранилище для результатов (для разработки)
# В продакшене используйте Redis или RabbitMQ
CELERY_BROKER_URL = 'memory://'  # Для разработки на Windows
CELERY_RESULT_BACKEND = 'django-db'  # Сохраняем результаты в БД
CELERY_RESULT_EXTENDED = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Планировщик задач
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Настройки для автоматических бэкапов
BACKUP_SCHEDULE_HOUR = 2  # 2 часа ночи
BACKUP_SCHEDULE_MINUTE = 0
BACKUP_ENABLE_NOTIFICATIONS = True  # Включить уведомления по email
